#include "swash.hpp"

Swash::Swash(Parameters & par):Solution(par){

	/**
	 * @details
	 * Defines the physical parameters and prints the header with the configuration.\n
	 * @param[in] par contains all the values from the parameters
	 * @par Modifies
	 * Solution#dx_ex, Solution#L, Solution#xex, Solution#zex to have the inclined plane configuration.
	 */

	lx_ = 20.;
	dx_ = lx_/nx_;
	e=0.1;
	a=1.5*sqrt(1+0.9*e) ;
	x0=0.7 ;
	eta0=1;
	A=1;
	flag=0;

	ta=0;

	if(1==par.get_choice()){
		namefile = "transient_leftbc.txt";
		head(par, "Solution over an inclined plane", "transient swash solution");
		sol =1;
		alpha =0.02 ;
		tf=15;
	}
	else{ //par.get_choice()=2
		namefile = "periodic_leftbc.txt";
		head(par, "Solution over an inclined plane", "periodic swash solution");
		sol =2;
		alpha =1.0/30 ;
		tf=12.28;
	}

	dt = 0.01;
	nt = tf/dt;		// to save the evolution of the left boundary condition


	//definition of the non-dimensional variables
	xexa=new double[nx_+1];
	zexa=new double[nx_+1];
	uexa=new double[nx_+1];
	hexa=new double[nx_+1];
	etaa=new double[nx_+1];

	uexa[0]=0.1;
	etaa[0]=eta0 ;
	hexa[0]=eta0+x0 ;
	speed_[0]=uexa[0]*sqrt(GRAV*alpha*lx_) ;
	depth_[0]=hexa[0]*alpha*lx_ ;

	for (int i=0 ; i<=nx_ ; i++){
		xs_[i] = (i-0.5)*dx_;
		bed_[i] = alpha*xs_[i]; //inclined plane
		xexa[i] = xs_[i]/lx_; //non-dimensionalization of xex
		zexa[i] = bed_[i]/(alpha*lx_); // non-dimensionalization of zex
	}

	param(lx_, dx_, alpha, e);


	ofstream outsave(namefile.c_str(),ios::out);
	outsave << "//******************************************************************************" << endl;
	outsave << "// Generated by " << VERSION <<" with " << nx_ << " cells."<<endl;
	outsave << "//******************************************************************************" << endl;
	outsave << "// Values of the left boundary condition (water height and discharge) " << endl;
	outsave << "// as a function of time (with dt="<<dt<<"s) for the Shallow Water code." << endl;
	outsave << "//******************************************************************************" << endl;
	outsave << "// The syntax of this file is adapted to the Shallow Water code FullSWOF_1D," << endl;
	outsave << "// see https://sourcesup.renater.fr/projects/fullswof-1d/ (v1.02.02):" <<endl;
	outsave << "// copy this file in the libboundaryconditions file: " << endl;
	outsave << "// bc_imp_height.cpp, at the beginning of method Bc_imp_height::calc ." << endl;
	outsave << "//******************************************************************************" << endl;
	outsave << " " << endl;
	outsave.close();


}


Swash::~Swash(){
}


void Swash::compute(){

	/**
	 * @details
	 * Computes the swash solutions of a wave on an inclined plane, see \cite Marche05, \cite CaGr58.
	 */

	double result [2]; //will contain the non-dimensional speed and free surface

	for (int n=0 ; n<=nt; n++){
		ta=sqrt(alpha*GRAV/lx_)*n*dt;
		flag=0;
		for (int i=1 ; i<=nx_ ; i++){
			result[0]=uexa[i-1] ;
			result[1]=etaa[i-1] ;
			ua_eta(x0,e,a,ta,xexa[i],result, sol) ; //fills the table result with speed and free surface
			uexa[i]=result[0] ;
			speed_[i]=uexa[i]*sqrt(GRAV*alpha*lx_) ; //dimensionalization of the speed of the wave
			etaa[i]=result[1];
			if (1==flag){
				depth_[i] =0;
			}
			else{
				hexa[i]=etaa[i]-(xexa[i]-x0);
				depth_[i]=hexa[i]*alpha*lx_ ; //dimensionalization of the water height
			}
		}
		leftcondition(n,depth_[1], speed_[1]);
	}

	//save_final_critical(xexa, hexa, uexa, zexa); gives the non-dimensional values instead of dimensional ones
	save_final_critical(xs_,depth_,speed_,bed_);

}



void Swash::ua_eta(double x0,double e, double a, double ta, double xa, double* result, int sol){

	/**
	 * @details
	 * Computes the velocity and free surface (using Newton algorithm) at one point and one time.
	 * @param[in] x0 abscissa changement
	 * @param[in] e the initial curvature of the wave
	 * @param[in] a the parameter a in the references
	 * @param[in] ta non dimentional time
	 * @param[in] xa non dimentional abscissa
	 * @param[in] result non-dimensional velocity and free surface at (xa,ta)
	 * @param[in] sol to choose the transient (sol=1) or periodic (sol=2) solution to compute
	 */

	double u1(result[0]), u2(result[0]+0.1), eta1(result[1]), eta2(result[1]+0.1) ; //initialization of Newton's algorithm
	int n (0) ;
	double A2(0.), B2(0.),C2(0.),D2(0.),E2(0.),F2(0.);
	double lambda, sigma ;
	if (isnan(u1)){u1=0.1;u2=0.2;}
	if (isnan(eta1)){eta1=0.05;eta2=0.1;}

	while((abs(u1-u2)>0.00001 && abs(eta1-eta2)>0.00001) && n<15) {//beginning of the algorithm
		eta2=eta1 ;
		u2=u1 ;
		if (eta2-(xa-x0)<=0) {
			u1=0 ;
			eta1=0 ;
			u2=0;
			eta2=0;
			flag=1;
		}

		else {
			if (1==sol){

				complex < double > A1,B1,C1,D1,E1,F1,X ;
				complex < double > i(0,1) ; //definition of the complex i

				lambda=2./a*(u2+ta); // This is tilde lambda
				sigma=4./a*sqrt(eta2-(xa-x0)); // This is tilde sigma
				X=pow(1.-i*lambda,2.)+pow(sigma,2.);

				/* We solve f1(v,eta) = 0 and f2(v,eta) = 0
					f1(v,eta) = -v +8e/a Im(...) and f2(v,eta) = -eta - v^2/2+e Re(1-...) (see refs.)
					thanks to Newton's method. The Jacobian matrix is
					(df1/dv , df1/deta ; df2/dv , df2/deta) */

				A1=(5.*i+4.*lambda)/pow(X,5./2.)-5.*i*pow(1.-i*lambda,2.)/pow(X,7./2.);
				A2=12.*e/pow(a,2.)*imag(A1)-1; //coefficient 1x1 of the Jacobian matrix

				B1=5.*(1.-i*lambda)/pow(X,7./2.)-4./pow(X,5./2.);
				B2=48.*e/pow(a,3.)*imag(B1); //coefficient 1x2 of the Jacobian matrix

				C1=4.*i/pow(X,3./2.)+15.*i*pow(1.-i*lambda,3.)/pow(X,7./2.)-(1.-i*lambda)*(21.*i+12.*lambda)/pow(X,5./2.);
				C2=-u2+e/a*real(C1); //coefficient 2x1 of the Jacobian matrix

				D1=(5.*pow(sigma,2.)-4.*i*lambda*X)/pow(X,7./2.);
				D2=12.*pow(a,-2.)*e*real(D1)-1; //coefficient 2x2 of the Jacobian matrix
	
				E1=4.*pow(X,-3./2.)-3.*(1.-i*lambda)/pow(X,5./2.);
				E2=2.*e/a*imag(E1)-u2;

				F1=(5.-4.*i*lambda)/pow(X,3./2.)-3.*pow(1.-i*lambda,2.)/pow(X,5./2.);
				F2=-pow(u2,2.)/2.+e-e/2.*real(F1)-eta2;
			}
			if (2==sol) {
				lambda=2.*(u2+ta);
				sigma=4.*sqrt(eta2-(xa-x0));

				/* We solve f1(v,eta) = 0 and f2(v,eta) = 0
					f1(v,eta) = -v +A J1(sigma) sin(lambda)/sigma and f2(v,eta) = -eta - v^2/2+A/4 J0(sigma)cos(lambda)
					thanks to Newton's method. The Jacobian matrix is
					(df1/dv , df1/deta ; df2/dv , df2/deta) */

				A2=-2.*A*J(1,sigma)*cos(lambda)/sigma-1.; //coefficient 1x1 of the Jacobian matrix

				B2=8.*A/pow(sigma,2.)*sin(lambda)*J(2,sigma) ; //coefficient 1x2 of the Jacobian matrix

				C2= -1./2.*(A*J(0,sigma)*sin(lambda)-u2); //coefficient 2x1 of the Jacobian matrix

				D2=-2*A/sigma*cos(lambda)*J(1,sigma)-1 ; //coefficient 2x2 of the Jacobian matrix

				E2=-A*J(1,sigma)*sin(lambda)/sigma-u2;

				F2=A/4.*J(0,sigma)*cos(lambda)-pow(u2,2.)/2-eta2 ;
			}

			u1=u2+(D2*E2-B2*F2)/(B2*C2-A2*D2);
			eta1=eta2+(F2*A2-C2*E2)/(B2*C2-A2*D2);
			n=n+1;
		}
	}
	result[0]=u1 ; result[1]=eta1 ;
}



void Swash::param(double L, double dx_ex, double alpha, double e) const{

	/**
	 * @details
	 * @param[in] L length of the domain
	 * @param[in] dx_ex space step
	 * @param[in] alpha the slope of the plane
	 * @param[in] e the initial curvature of the wave
	 */

	cout << "# PARAMETERS OF THE SOLUTION"<< endl;
	cout << "# " << endl;
	cout << "# Length of the domain: " << L << " meters"<<endl;
	cout << "# Space step: "<< dx_ex << " meters"<< endl;
	cout << "# Number of cells: " << nx_ << endl;
	cout << "# Topography: z(x) = " << alpha << " x " << endl;
	cout << "# Time value: " << tf << " seconds" << endl;
	cout << "# Initial curvature of the wave: " << e << endl;
	cout << "# Shift on the abscissa, x0: " << x0 << endl;
	cout << "# Left boundary condition: see file "<<namefile.c_str()<<" ." << endl;
	cout << "# " << endl;
	cout << "##############################################################################" << endl;
}

void Swash::leftcondition(int n, double hexl, double uexl) const{
	
	/**
	 * @details
	 * Saves the left boundary condition (h and q=hu) in the file transient_leftbc.txt or periodic_leftbc.txt.
	 * @param[in] n current time iteration
	 * @param[in] hexl left value of the water height
	 * @param[in] uexl left value of the velocity
	 */

	ofstream outsave(namefile.c_str(),ios::app);

	if (0==n){}
	else if (1==n){
		outsave << "if (time<"<< n*dt<<"){ hfix = "<<hexl<<"; qfix ="<<hexl*uexl<<"; }" << endl;
	}
	else if (n==nt){
		outsave << "else { hfix = "<<hexl<<"; qfix ="<<hexl*uexl<<"; }" << endl;
	}
	else{
		outsave << "else if (time<"<< n*dt<<"){ hfix = "<<hexl<<"; qfix ="<<hexl*uexl<<"; }" << endl;
	}

	outsave.close();

}

double Swash::J(int k, double x){

	/**
	 * @details
	 * Computes the value of the kth Bessel function (k=0,1 or 2) at x.
	 * @param[in] k the number of the Bessel function (k=0,1 or 2)
	 * @param[in] x the point to evaluate the Bessel function
	 */

	double j, tmp, x2;
	int kf;

	kf = max(1,k);
	j = pow((x/2),k)/kf;
	tmp = j;
	x2 = pow((x/2),2);
	for (int comp =1; comp <=30; comp ++){
		tmp *= -x2/(comp*(comp+k));
		j+=tmp;
	}
	return j;
}
